/**
 * This node script naively takes `jsx-h.d.ts` as source and writes a new `jsx.d.ts`:
 *
 * - Takes `jsx-h.d.ts` as source
 * - Removes `FunctionElement` from `type Element`
 * - Strips `FunctionMaybe` from elements attributes
 * - Writes a new `jsx.d.ts`
 *
 * @see https://github.com/ryansolid/dom-expressions/issues/408
 */

import fs from 'fs';
import { execSync as $ } from 'child_process';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const jsxHPath = path.join(__dirname, 'jsx-h.d.ts');
const jsxHTempPath = path.join(__dirname, 'jsx-h.temp.d.ts');
const jsxOutPath = path.join(__dirname, 'jsx.d.ts');

// ensures source is always pretty printed at commit and free of errors

$(`prettier "${jsxHPath}" --write`);

// copy source to temp file

fs.copyFileSync(jsxHPath, jsxHTempPath);

// make each propertyDecorator a one liner in temp file

$(`prettier "${jsxHTempPath}" --write --no-editorconfig --print-width 100000`);

// read source

const source = fs.readFileSync(jsxHTempPath).toString().split('\n');

// remove `-h` TYPE

for (let i = 0; i < source.length; i++) {
  const line = source[i].trim();

  if (line.startsWith('type Element')) {
    // remove `| FunctionElement` from 'type Element'
    source[i] = line.replace('| FunctionElement', '');
  } else if (!line.startsWith('type FunctionMaybe') && line.includes('FunctionMaybe')) {
    // unwrap `FunctionMaybe'
    source[i] = line.replace(/: FunctionMaybe<([^>]+)>;$/, ': $1');
  }
}

// write result

const banner = `
// noinspection JSUnusedGlobalSymbols
/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-explicit-any */

/**
	THIS FILE IS GENERATED BY \`./jsx-update.mjs\`.
	PLEASE UPDATE \`jsx-h.d.ts\` INSTEAD AND RUN \`node jsx-update.mjs\`.
*/

`;
fs.writeFileSync(jsxOutPath, banner + source.join('\n'));

// reformat file

$(`prettier "${jsxOutPath}" --write`);

// discard temporal file

fs.unlink(jsxHTempPath, () => {});
